<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Ajaxcartpro
 * @copyright  Copyright (c) 2009-2010 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
 ?>
<div class="ajaxcartpro_confirm" style="display: none;">
	<p><span id="acp_product_name"><?php echo $this->__('Item(s)') ?></span><?php echo $this->__(' added to cart') ?></p>
		<a href="#" id="aw_acp_continue" class="focus"><?php echo $this->__('Continue shopping')?><?php echo Mage::helper('ajaxcartpro')->displayCountdown() ?></a>

	<?php echo $this->__('or')?>
	<a href="<?php echo Mage::getUrl('checkout/cart')?>" id="aw_acp_checkout">
		<?php echo $this->__('View cart &amp; checkout')?>
	</a>
</div>
