<?php

/**
 * Magictoolbox product list template for Magento store.
 * Allow use MagicTools on product list page.
 * @mail support@magictoolbox.com
 */

    foreach ($_productCollection as $_product) {

        $_product = Mage::getModel('catalog/product')->load($_product->getId());

        if($_product->getImage() && $_product->getImage() != 'no_selection') {
            $title = $this->htmlEscape($_product->getName());
            $description = $this->htmlEscape($_product->getDescription());
            $shortDescription = $this->htmlEscape($_product->getShortDescription());
            //$thumb = $magicToolboxHelper->magicToolboxResizer($_product, 'small_image', 'category-thumb');
            //$img = $magicToolboxHelper->magicToolboxResizer($_product, 'image');
            $_image_file = $_product->getSmall_image();
            $img = $this->helper('catalog/image')->init($_product, 'image', $_image_file)->__toString();
            list($w, $h) = $magicToolboxHelper->magicToolboxGetSizes('category-thumb', $this->helper('catalog/image')->getOriginalSizeArray());
            $thumb = $this->helper('catalog/image')->init($_product, 'small_image', $_image_file)->resize($w, $h)->__toString();

            if($tool->params->checkValue('link-to-product-page', 'Yes')) {
                $link = $_product->getProductUrl();
            } else {

                $link = '';
            }



            if($tool->params->checkValue('drag-mode', 'Yes')) { //onclick only if drag mode is disabled
                $link = '';
            }




            $id = $_product->getId();
            $html = $tool->template(compact("id", "title", "description", "shortDescription", "img", "thumb", "link"));

            if($tool->params->checkValue('show-selectors-on-category-page', 'Yes')) {
                $gallery = Mage::getModel('catalog/product')->load($id)->getMediaGalleryImages();
                $html .= '<div class="MagicToolboxSelectorsContainer">';
                foreach($gallery  as $_image) {
                    //$medium = $magicToolboxHelper->magicToolboxResizer($_product, 'small_image', 'category-thumb', $_image->getFile());
                    //$thumb = $magicToolboxHelper->magicToolboxResizer($_product, 'thumbnail', 'category-selector', $_image->getFile());
                    //$img = $magicToolboxHelper->magicToolboxResizer($_product, 'image', null, $_image->getFile());
                    $_image_file = $_image->getFile();
                    $_image_path  = $_image->getPath();
                    list($w, $h) = $magicToolboxHelper->magicToolboxGetSizes('category-thumb', getimagesize($_image_path));
                    $medium = $this->helper('catalog/image')->init($_product, 'small_image', $_image_file)->resize($w, $h)->__toString();
                    list($w, $h) = $magicToolboxHelper->magicToolboxGetSizes('category-selector', getimagesize($_image_path));
                    $thumb = $this->helper('catalog/image')->init($_product, 'thumbnail', $_image_file)->resize($w, $h)->__toString();
                    $img = $this->helper('catalog/image')->init($_product, 'image', $_image_file)->__toString();

                    $title = $this->htmlEscape($_image->getLabel());
                    $a = $tool->subTemplate(compact("id", "img", "thumb", "medium", "title"));
                    $html .= $a;
                }
                $html .= '</div>';
            }

            $html = '<div class="MagicToolboxContainer">' . $html . '</div>';

            $pattern = '<a[^>]+href=\"' . preg_quote($_product->getProductUrl(), '/') . '\"[^>]*>\s*<img[^>]+\/>\s*<\/a>';
            $pattern = '/' . $pattern . '/is';
            $contents_new = preg_replace($pattern, $html, $contents);
            if($contents_new == $contents) {
                $hash = preg_replace('/^.*?image\/([a-z0-9]+)\/.*$/is', '$1', $img);
                //$name = preg_replace('/^.*?image\/([a-z0-9]+)\/.*?\/([^\/]+)$/is', '$2', $img);
                $name = $this->helper('catalog/image')->init($_product, 'small_image');
                $name = preg_replace('/^.*?image\/([a-z0-9]+)\/.*?\/([^\/]+)$/is', '$2', $name);
                $pattern = '<img[^>]+src=\"[^\"]*\/' . preg_quote($hash, '/') . '\/[^\"]*\/' . preg_quote($name, '/') . '\"[^>]*\/>';
                //$pattern = '/' . $pattern . '/is';
                $contents_new = preg_replace('/<a[^>]+>\s*' . $pattern . '\s*<\/a>/is', $html, $contents);
                if($contents_new == $contents) {
                    $contents_new = preg_replace('/' . $pattern . '/is', $html, $contents);
                }
            }
            $contents = $contents_new;
        }
    }

?>
