<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Ajaxcartpro
 * @copyright  Copyright (c) 2009-2010 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */

 ?>
<div id="acp_configurable_block">
    <div id="acp-overlay"></div>
    <script type="text/javascript">
        optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
    </script>
    <?php $_product = $this->getProduct() ?>
    <form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post"
          id="product_addtocart_form_acp"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" value="<?php $_product->getId() ?>" name="product">
        <?php echo $this->getChildHtml('product_js');?>
        <div id="acp_product_options">
            <div class="product-options" id="product-options-wrapper" style="margin:0">
                <div class="product-name"><?php echo $_product->getName() ?></div>
                <div style="display:none">
                    <?php echo $this->getChildHtml('product_type_data') ?>
                </div>
                <?php echo str_replace('var ', '', $this->getChildHtml('product_options'));?>
                <?php echo $this->getChildHtml('product_configurable_options');?>
                <?php echo $this->getChildHtml('product_downloadable_options');?>
                <?php echo $this->getChildHtml('product_price');?>
                <div style="margin:5px 0px 20px 20px">
                    <a href="#" id="aw_acp_continue" onclick = "$('acp_configurable_block').remove();" style="float:left; margin: 0 5px">
                        <?php echo $this->__('Cancel')?>
                    </a>
                    <a href="#" id="aw_acp_checkout" class="focus" onclick="acpSubmit(); return false;" style="float:left; margin: 0 5px">
                        <?php echo $this->__('Add to cart')?>
                    </a>
                </div>
            </div>
        </div>
    </form>
</div>
