<div class="onestepcheckout-coupons">
  <div id="coupon-notice" style="display: none;"></div>
  <label for="id_couponcode">Promotional Code:</label>
  <input class="input-text" type="text" name="onestepcheckout-couponcode" id="id_couponcode" value="" />
  <button id="onestepcheckout-coupon-add" class="button" type="button" onclick="couponcodeadd.save();">Apply Code</button>
  <button id="onestepcheckout-coupon-remove" class="button" type="button" style="display: none;" onclick="couponcoderemove.save();">Cancel Coupon</button>
</div>