<?php $url = Mage::getUrl();
$url = str_replace( "/us/", "/", $url );
$url = str_replace( "/eu/", "/", $url );
?>
<link rel="stylesheet" href="<?php echo $url?>culture/wp-content/themes/etiquette/style.css" type="text/css" media="screen" />
<?php
function get_data($url)
{
  $ch = curl_init();
  $timeout = 5;
  curl_setopt($ch,CURLOPT_URL,$url);
  curl_setopt($ch,CURLOPT_RETURNTRANSFER,1);
  curl_setopt($ch,CURLOPT_CONNECTTIMEOUT,$timeout);
  $data = curl_exec($ch);
  curl_close($ch);
  return $data;
}

$cont = get_data( "http://www.etiquetteclothiers.com/culture/special-edition-2/" );
echo( str_replace( "/culture/specialedition", "/se/specialedition", $cont ) );
?>
<hr />


</div>

</div>
 <script type="text/javascript" src="<?php echo $url?>culture/wp-content/themes/etiquette/assets/js/cycle.js"></script>

 <script type="text/javascript" src="<?php echo $url?>culture/wp-content/themes/etiquette/assets/js/script.js"></script>
